import { expect, test, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'

async function blank(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: '＋ 新建作品', exact: true }).click()
  await page.getByRole('spinbutton', { name: '速度 BPM' }).fill('120')
}
async function readProject(page: Page) {
  return page.evaluate(() => JSON.parse(localStorage.getItem('sonora.library.v1')!)[0])
}
async function pianoNotes(page: Page) {
  await page.getByRole('button', { name: '声部编辑', exact: true }).click()
  await page.getByRole('button', { name: 'C4 1', exact: true }).click()
  await page.getByRole('button', { name: 'E4 3', exact: true }).click()
}

test('expanded instrument library plays decoded guitar bass and drums, and saves percussion notation', async ({ page }) => {
  const errors: string[] = [], assets = new Set<string>()
  page.on('pageerror', (error) => errors.push(error.message))
  page.on('response', (response) => { if (response.status() === 200 && /samples\/(guitar-|bass-|drum-)/.test(response.url())) assets.add(response.url()) })
  await page.addInitScript(() => {
    ;(window as any).__decodedSamples = 0
    ;(window as any).__samplePeak = 0
    const decode = BaseAudioContext.prototype.decodeAudioData
    BaseAudioContext.prototype.decodeAudioData = function (...args: any[]) {
      const result = Reflect.apply(decode, this, args)
      result.then((buffer: AudioBuffer) => {
        ;(window as any).__decodedSamples++
        const data = buffer.getChannelData(0)
        for (const value of data) (window as any).__samplePeak = Math.max((window as any).__samplePeak, Math.abs(value))
      })
      return result
    }
  })
  await page.goto('/')
  await page.locator('.project-card').filter({ hasText: 'Sonora 演示：吉他与鼓' }).getByRole('button', { name: '打开作品 ↗' }).click()
  for (const name of ['木吉他', '电吉他', '电贝斯', '电子鼓组']) await expect(page.getByRole('button', { name: `＋ ${name}`, exact: true })).toBeVisible()
  await page.getByRole('button', { name: '从当前位置播放' }).click()
  await expect(page.getByRole('button', { name: '停止播放' })).toBeVisible()
  await expect.poll(() => page.evaluate(() => (window as any).__decodedSamples)).toBeGreaterThanOrEqual(18)
  expect(await page.evaluate(() => (window as any).__samplePeak)).toBeGreaterThan(.01)
  expect(assets.size).toBe(18)
  await expect(page.getByRole('button', { name: '从当前位置播放' })).toBeVisible({ timeout: 15000 })
  const drumTrack = page.locator('.track-card').filter({ has: page.getByRole('textbox', { name: '电子鼓组名称', exact: true }) })
  await drumTrack.dblclick()
  await expect(page.getByRole('region', { name: '电子鼓垫' }).getByRole('button')).toHaveCount(9)
  await expect(page.getByRole('combobox', { name: '声部调号', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: '移调整个声部' })).toBeDisabled()
  await expect(page.locator('.staff[data-clef="percussion"]')).toHaveCount(1)
  await expect(page.locator('.key-signature')).toHaveCount(0)
  await expect(page.locator('.drum-cross')).not.toHaveCount(0)
  for (const name of ['底鼓', '军鼓', '闭合踩镲', '开放踩镲', '低通鼓', '中通鼓', '高通鼓', '碎音镲', '叮叮镲']) await page.getByRole('button', { name: `输入${name}`, exact: true }).click()
  await page.screenshot({ path: 'test-results/expanded-instruments.png', fullPage: true })
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('sonora.library.v1')!).find((project: { id: string }) => project.id === 'sonora-band-demo-v1'))
  expect(stored.tracks[3].notes.slice(-9).map((note: { midi: number }) => note.midi)).toEqual([36, 38, 42, 46, 41, 45, 48, 49, 51])
  await page.getByRole('button', { name: '生成总谱', exact: true }).click()
  await expect(page.locator('.staff[data-clef="bass"]')).toHaveCount(1)
  await expect(page.locator('.percussion-clef')).toHaveCount(1)
  await page.getByRole('button', { name: '＋ 电贝斯', exact: true }).click()
  await page.getByRole('button', { name: '声部编辑', exact: true }).click()
  await page.getByRole('button', { name: 'E1 3', exact: true }).click()
  const bassPitch = await page.evaluate(() => JSON.parse(localStorage.getItem('sonora.library.v1')!).find((project: { id: string }) => project.id === 'sonora-band-demo-v1').tracks.at(-1).notes[0].midi)
  expect(bassPitch).toBe(28)
  expect(errors).toEqual([])
})

test('missing drum samples fall back without errors on simultaneous kick snare and hi-hat', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.route('**/samples/drum-*.wav', (route) => route.abort())
  await page.goto('/')
  await page.locator('.project-card').filter({ hasText: 'Sonora 演示：吉他与鼓' }).getByRole('button', { name: '打开作品 ↗' }).click()
  await page.getByRole('spinbutton', { name: '速度 BPM' }).fill('240')
  await page.getByRole('button', { name: '从当前位置播放' }).click()
  await expect(page.getByRole('button', { name: '停止播放' })).toBeVisible()
  await expect(page.getByRole('button', { name: '从当前位置播放' })).toBeVisible({ timeout: 10000 })
  expect(errors).toEqual([])
})

test('symbol demo is added once, shows every mark and plays all sections with real audio output', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.addInitScript(() => {
    const peaks: number[] = []
    ;(window as any).__demoAudioPeaks = peaks
    const connect = AudioNode.prototype.connect
    AudioNode.prototype.connect = function (...args: any[]) {
      const target = args[0]
      if (target instanceof AudioDestinationNode) {
        const analyser = this.context.createAnalyser(), sink = this.context.createGain()
        analyser.fftSize = 256; sink.gain.value = 0
        Reflect.apply(connect, this, [analyser]); Reflect.apply(connect, analyser, [sink]); Reflect.apply(connect, sink, [target])
        const samples = new Float32Array(analyser.fftSize)
        setInterval(() => { analyser.getFloatTimeDomainData(samples); peaks.push(Math.max(...samples.map(Math.abs))) }, 100)
      }
      return Reflect.apply(connect, this, args)
    }
  })
  await page.goto('/')
  const card = page.locator('.project-card').filter({ hasText: 'Sonora 演示：全符号试奏' })
  await expect(card).toHaveCount(1)
  await page.reload()
  await expect(card).toHaveCount(1)
  await card.getByRole('button', { name: '打开作品 ↗' }).click()
  await expect(page.getByRole('region', { name: '全符号试听导览' })).toBeVisible()
  await page.getByRole('button', { name: '5.0s · 升降还原', exact: true }).click()
  await expect(page.getByRole('spinbutton', { name: '当前位置秒数' })).toHaveValue('5')
  await page.getByRole('button', { name: '回到开头', exact: true }).click()
  await page.screenshot({ path: 'test-results/symbol-demo-timeline.png', fullPage: true })
  await page.getByRole('button', { name: '生成总谱', exact: true }).click()
  const score = page.locator('.generated-score')
  await expect(score.locator('.staff')).toHaveCount(6)
  for (const symbol of ['♯', '♭', '♮']) expect(await score.locator('.score-accidental').allTextContents()).toContain(symbol)
  await expect(score.locator('.score-tie')).not.toHaveCount(0)
  await expect(score.locator('.score-fermata')).toHaveCount(2)
  await expect(score.locator('.score-rest')).not.toHaveCount(0)
  await page.getByRole('button', { name: '从当前位置播放' }).click()
  await expect(page.getByRole('button', { name: '停止播放' })).toBeVisible()
  await expect.poll(() => page.evaluate(() => Math.max(...(window as any).__demoAudioPeaks)), { timeout: 10000 }).toBeGreaterThan(.001)
  await expect(page.getByRole('button', { name: '从当前位置播放' })).toBeVisible({ timeout: 32000 })
  expect(errors).toEqual([])
  const audibleSamples = await page.evaluate(() => (window as any).__demoAudioPeaks.filter((peak: number) => peak > .001).length)
  expect(audibleSamples).toBeGreaterThan(50)
})

test('piano grand staff renders both key signatures and preserves manual staff assignment', async ({ page }) => {
  await blank(page)
  await page.getByRole('button', { name: '声部编辑', exact: true }).click()
  const keyboard = page.getByRole('region', { name: '多八度音符键盘' })
  for (const name of ['C3 1', 'C4 1', 'E5 3']) await keyboard.getByRole('button', { name, exact: true }).click()
  const treble = page.locator('.staff[data-clef="treble"]'), bass = page.locator('.staff[data-clef="bass"]')
  await expect(treble.locator('.score-note')).toHaveCount(2)
  await expect(bass.locator('.score-note')).toHaveCount(1)
  await expect(bass.locator('.score-clef')).toHaveText('𝄢')
  await expect(treble.locator('.score-clef')).toHaveText('𝄞')
  await expect(bass.locator('.score-rest')).not.toHaveCount(0)
  await page.getByRole('combobox', { name: '声部调号', exact: true }).selectOption('D')
  for (const staff of [treble, bass]) await expect(staff.locator('.key-signature text')).toHaveText(['♯', '♯'])
  await page.getByRole('combobox', { name: '声部调号', exact: true }).selectOption('C')
  await expect(page.locator('.key-signature text')).toHaveCount(0)
  await page.getByRole('combobox', { name: '声部调号', exact: true }).selectOption('B♭')
  for (const staff of [treble, bass]) await expect(staff.locator('.key-signature text')).toHaveText(['♭', '♭'])
  await expect(bass.locator('.key-signature text').first()).toHaveAttribute('y', '109')
  await treble.locator('.score-note').filter({ has: page.locator('text.pitch-caption').filter({ hasText: /^C4$/ }) }).click()
  await page.getByRole('combobox', { name: '音符谱表' }).selectOption('bass')
  await expect(bass.locator('.score-note')).toHaveCount(2)
  const project = await readProject(page)
  expect(project.tracks[0].notes.map((note: { midi: number; onsetBeats: number }) => [note.midi, note.onsetBeats])).toEqual([[48, 0], [60, 1], [76, 2]])
  expect(project.tracks[0].notes[1].staff).toBe('bass')
  await page.getByRole('textbox', { name: '作品名称' }).fill('钢琴双谱表验收')
  await page.reload()
  await page.locator('.project-card').filter({ hasText: '钢琴双谱表验收' }).getByRole('button', { name: '打开作品 ↗' }).click()
  await page.getByRole('button', { name: '生成总谱', exact: true }).click()
  await expect(bass.locator('.score-note')).toHaveCount(2)
  await expect(page.locator('.key-signature text')).toHaveCount(4)
  await page.locator('.generated-score').screenshot({ path: 'test-results/piano-grand-staff.png' })
  const pendingDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载总谱 SVG' }).click()
  const download = await pendingDownload
  const svg = await readFile((await download.path())!, 'utf8')
  expect(svg).toContain('data-clef="treble"')
  expect(svg).toContain('data-clef="bass"')
  expect(svg).toContain('grand-staff-connector')
})

test('the continuous keyboard enters absolute pitches across octaves and scrolls on narrow screens', async ({ page }) => {
  await blank(page)
  await page.getByRole('button', { name: '声部编辑', exact: true }).click()
  const keyboard = page.getByRole('region', { name: '多八度音符键盘' })
  await expect(keyboard.getByRole('button')).toHaveCount(37)
  for (const name of ['C3 1', 'C4 1', 'C5 1', 'C6 1', 'C♯4 ♯1']) {
    await keyboard.getByRole('button', { name, exact: true }).click()
  }
  expect((await readProject(page)).tracks[0].notes.map((note: { midi: number }) => note.midi)).toEqual([48, 60, 72, 84, 61])
  await page.screenshot({ path: 'test-results/multi-octave-keyboard.png', fullPage: true })
  await page.getByRole('checkbox', { name: '扩展至 C2–C7' }).check()
  await expect(keyboard.getByRole('button')).toHaveCount(61)
  for (const name of ['C2 1', 'C7 1']) await keyboard.getByRole('button', { name, exact: true }).click()
  expect((await readProject(page)).tracks[0].notes.slice(-2).map((note: { midi: number }) => note.midi)).toEqual([36, 96])
  await page.setViewportSize({ width: 390, height: 844 })
  await keyboard.getByRole('button', { name: 'C4 1', exact: true }).click()
  expect((await readProject(page)).tracks[0].notes.at(-1).midi).toBe(60)
  expect(await keyboard.evaluate((element) => element.scrollWidth > element.clientWidth)).toBe(true)
  const bounds = (await keyboard.boundingBox())!
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(390)
})

test('clip edges align across tracks with guides and allow mouse and keyboard fine adjustment', async ({ page }) => {
  await blank(page)
  await pianoNotes(page)
  await page.getByRole('spinbutton', { name: '片段起始秒数' }).fill('2')
  await page.getByRole('button', { name: '＋ 钢琴', exact: true }).click()
  for (const name of ['C4 1', 'E4 3']) await page.getByRole('button', { name, exact: true }).click()
  await page.getByRole('button', { name: '时间轴', exact: true }).click()
  const clip = page.locator('.timeline-track').filter({ hasText: '钢琴 2' }).locator('.music-clip')
  const guide = page.locator('.alignment-guide')
  async function dragBy(pixels: number) {
    const box = (await clip.boundingBox())!
    await page.mouse.move(box.x + 15, box.y + 25)
    await page.mouse.down()
    await page.mouse.move(box.x + 15 + pixels, box.y + 25, { steps: 8 })
  }
  await dragBy(155)
  await expect(clip).toHaveAttribute('title', '片段 1 · 2.00 秒')
  await expect(guide).toHaveCount(2)
  await expect(guide.first()).toHaveAttribute('data-seconds', '2')
  await page.screenshot({ path: 'test-results/alignment-guides.png', fullPage: true })
  await page.mouse.up()
  await expect(guide).toHaveCount(0)
  await clip.press('ArrowLeft')
  await expect(clip).toHaveAttribute('title', '片段 1 · 1.99 秒')
  await clip.press('Shift+ArrowRight')
  await expect(clip).toHaveAttribute('title', '片段 1 · 2.09 秒')
  await page.keyboard.down('Alt')
  await dragBy(-4)
  await expect(guide).toHaveCount(0)
  await page.mouse.up()
  await page.keyboard.up('Alt')
  await expect(clip).toHaveAttribute('title', '片段 1 · 2.04 秒')
  // The moving clip's end can align to the other clip's start.
  await dragBy(-78)
  await expect(clip).toHaveAttribute('title', '片段 1 · 1.00 秒')
  await expect(guide).toHaveCount(1)
  await expect(guide).toHaveAttribute('data-seconds', '2')
  await page.mouse.up()
  // Escape cancels the preview without altering stored notes.
  await dragBy(80)
  await page.keyboard.press('Escape')
  await page.mouse.up()
  await expect(clip).toHaveAttribute('title', '片段 1 · 1.00 秒')
  const project = await readProject(page)
  expect(project.tracks[0].notes.map((note: { onsetBeats: number }) => note.onsetBeats)).toEqual([4, 5])
  expect(project.tracks[1].notes.map((note: { onsetBeats: number }) => note.onsetBeats)).toEqual([2, 3])
  await page.getByRole('checkbox', { name: '自动对齐' }).uncheck()
  await page.getByRole('combobox', { name: '时间轴吸附' }).selectOption('0')
  await dragBy(77)
  await expect(guide).toHaveCount(0)
  await page.mouse.up()
  await expect(clip).toHaveAttribute('title', '片段 1 · 1.96 秒')
})

test('dragging a split clip leaves the other clip in place and creates rests', async ({ page }) => {
  await blank(page)
  await pianoNotes(page)
  await page.locator('.score-note').filter({ has: page.locator('text').filter({ hasText: 'E4' }) }).click()
  await page.getByRole('button', { name: '在选中音符处分割' }).click()
  await page.getByRole('button', { name: '时间轴', exact: true }).click()
  const clip = page.locator('.music-clip').filter({ hasText: '片段 2' })
  const box = (await clip.boundingBox())!
  await page.mouse.move(box.x + 8, box.y + 12)
  await page.mouse.down()
  await page.mouse.move(box.x + 168, box.y + 12, { steps: 12 })
  await page.mouse.up()
  await expect(clip).toHaveAttribute('title', '片段 2 · 2.50 秒')
  const project = await readProject(page)
  expect(project.tracks[0].notes.map((note: { onsetBeats: number }) => note.onsetBeats)).toEqual([0, 5])
  await page.getByRole('button', { name: '声部编辑', exact: true }).click()
  await expect(page.locator('.score-rest')).not.toHaveCount(0)
  await page.screenshot({ path: 'test-results/drag-and-rests.png', fullPage: true })
})

test('the playhead drags, playback advances from that position and stop freezes it', async ({ page }) => {
  await page.goto('/')
  await page.locator('.project-card').filter({ hasText: 'Sonora 示例：晨光' }).getByRole('button', { name: '打开作品 ↗' }).click()
  const pointer = page.getByRole('slider', { name: '播放时间指针' })
  const box = (await pointer.boundingBox())!
  await page.mouse.move(box.x + 1, box.y + 7)
  await page.mouse.down()
  await page.mouse.move(box.x + 81, box.y + 7, { steps: 8 })
  await page.mouse.up()
  await expect(page.getByRole('spinbutton', { name: '当前位置秒数' })).toHaveValue('1.01')
  await page.getByRole('button', { name: '从当前位置播放' }).click()
  await expect(page.getByRole('button', { name: '停止播放' })).toBeVisible()
  await expect.poll(async () => Number(await pointer.getAttribute('aria-valuenow'))).toBeGreaterThan(1.3)
  await page.getByRole('button', { name: '停止播放' }).click()
  const stopped = await pointer.getAttribute('aria-valuenow')
  await page.waitForTimeout(300)
  expect(await pointer.getAttribute('aria-valuenow')).toBe(stopped)
})

test('two piano parts retain independent keys and meters in the generated SVG', async ({ page }) => {
  await blank(page)
  await pianoNotes(page)
  await page.getByRole('combobox', { name: '声部拍号', exact: true }).selectOption('3/4')
  await page.getByRole('combobox', { name: '移调目标调号' }).selectOption('D')
  await page.getByRole('button', { name: '移调整个声部' }).click()
  await page.getByRole('button', { name: '＋ 钢琴', exact: true }).click()
  await page.getByRole('combobox', { name: '声部调号', exact: true }).selectOption('F')
  await page.getByRole('combobox', { name: '声部拍号', exact: true }).selectOption('7/8')
  await page.getByRole('button', { name: /^C4 / }).click()
  const project = await readProject(page)
  expect(project.tracks.map((track: { keySignature: string; timeSignature: string }) => [track.keySignature, track.timeSignature])).toEqual([['D', '3/4'], ['F', '7/8']])
  expect(project.tracks[0].notes.map((note: { midi: number }) => note.midi)).toEqual([62, 66])
  expect(project.tracks[1].notes[0].midi).toBe(60)
  expect(project.tracks[0].color).not.toBe(project.tracks[1].color)
  await page.getByRole('button', { name: '生成总谱', exact: true }).click()
  await expect(page.locator('.part-setting')).toHaveText(['D 大调 · 3/4', 'F 大调 · 7/8'])
  await expect(page.locator('.generated-score .score-rest')).not.toHaveCount(0)
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载总谱 SVG' }).click()
  expect((await download).suggestedFilename()).toContain('总谱.svg')
  await page.screenshot({ path: 'test-results/mixed-meter-score.png', fullPage: true })
  await page.getByRole('checkbox', { name: '钢琴 2加入总谱' }).uncheck()
  await expect(page.locator('.part-setting')).toHaveText(['D 大调 · 3/4'])
})

test('clip offset, independent settings and multiple projects survive a reload', async ({ page }) => {
  await blank(page)
  await pianoNotes(page)
  await page.getByRole('spinbutton', { name: '片段起始秒数' }).fill('3')
  await page.getByRole('combobox', { name: '声部拍号', exact: true }).selectOption('5/4')
  await page.getByRole('textbox', { name: '作品名称' }).fill('时间轴验收作品')
  await page.reload()
  await page.locator('.project-card').filter({ hasText: '时间轴验收作品' }).getByRole('button', { name: '打开作品 ↗' }).click()
  await expect(page.locator('.music-clip')).toHaveAttribute('title', '片段 1 · 3.00 秒')
  await page.getByRole('button', { name: '声部编辑', exact: true }).click()
  await expect(page.getByRole('combobox', { name: '声部拍号', exact: true })).toHaveValue('5/4')
  await expect(page.locator('.score-rest')).not.toHaveCount(0)
})
