import { useEffect, useRef, useState, type CSSProperties } from 'react'
import { formatProjectDate, loadProjects, saveProjects } from './projectStore'
import {
  beatsPerMeasure, createBlankProject, defaultSpellingForKey, durationToBeats, isAccidental,
  midiToJianpu, midiToName, midiToStaffY, newNote, newTrack, noteOnsets, pitches, trackDurationBeats,
  type AccidentalSpelling, type Duration, type InstrumentId, type KeySignature, type NoteEvent,
  type ProjectData, type TimeSignature, type Track,
} from './workspace'

const durations: { value: Duration; label: string; symbol: string }[] = [
  { value: 2, label: '倍全音符', symbol: '𝅜' }, { value: 1, label: '全音符', symbol: '𝅝' },
  { value: 0.5, label: '二分音符', symbol: '𝅗𝅥' }, { value: 0.25, label: '四分音符', symbol: '♩' },
  { value: 0.125, label: '八分音符', symbol: '♪' },
]
const instrumentMeta: Record<InstrumentId, { name: string; icon: string }> = {
  piano: { name: '钢琴', icon: '♬' }, violin: { name: '小提琴', icon: '𝄞' },
  cello: { name: '大提琴', icon: '𝄢' }, flute: { name: '长笛', icon: '♩' },
}

function Home({ projects, onCreate, onOpen }: { projects: ProjectData[]; onCreate: () => void; onOpen: (id: string) => void }) {
  return <main className="home-shell">
    <header className="home-topbar"><div className="brand-mark">S</div><div className="brand-copy"><strong>Sonora</strong><span>SCORE LIBRARY</span></div><button className="primary-action" onClick={onCreate}>＋ 新建作品</button></header>
    <section className="home-hero"><p className="eyebrow">MY MUSIC / 本地作品库</p><h1>先选择作品，<br /><span>再进入你的音乐工作台。</span></h1><p>每个作品独立保存总谱、声部、速度、调号和拍号。</p></section>
    <section className="project-library"><div className="library-heading"><h2>作品</h2><span>{projects.length} FILES</span></div><div className="project-grid">
      <button className="new-project-card" onClick={onCreate}><strong>＋</strong><span>创建空白作品</span><small>从一条空钢琴音轨开始</small></button>
      {projects.map((project) => <article className="project-card" key={project.id} onDoubleClick={() => onOpen(project.id)}>
        <div className="score-preview" aria-hidden="true">{[0, 1, 2, 3, 4].map((line) => <i key={line} style={{ top: `${34 + line * 12}px` }} />)}{project.tracks.slice(0, 4).flatMap((track, trackIndex) => track.notes.slice(0, 4).map((note, noteIndex) => <b key={`${track.id}-${note.id}`} style={{ left: `${28 + noteIndex * 42 + trackIndex * 8}px`, top: `${48 - (note.midi - 60) * 2}px`, background: track.color }} />))}</div>
        <div className="project-card-copy"><div>{project.example && <em>样例</em>}<strong>{project.title}</strong></div><p>{project.tracks.length} 个声部 · {project.keySignature} 大调 · {project.timeSignature}</p><small>更新于 {formatProjectDate(project.updatedAt)}</small></div>
        <button onClick={() => onOpen(project.id)}>打开作品</button>
      </article>)}
    </div></section>
  </main>
}

function Staff({ project, track, selectedId, activeStep, onSelect }: { project: ProjectData; track: Track; selectedId: string | null; activeStep: number; onSelect: (id: string) => void }) {
  const onsets = noteOnsets(track.notes), measureBeats = beatsPerMeasure(project.timeSignature)
  const measures = Math.max(1, Math.ceil(Math.max(measureBeats, trackDurationBeats(track.notes)) / measureBeats))
  const pxPerBeat = 62, startX = 156, width = Math.max(820, startX + measures * measureBeats * pxPerBeat + 42)
  const [numerator, denominator] = project.timeSignature.split('/'), clef = track.instrument === 'cello' ? '𝄢' : '𝄞'
  const fallbackSpelling = defaultSpellingForKey(project.keySignature)
  return <div className="staff-scroll" aria-label={`${track.name}五线谱`}><svg className="staff" viewBox={`0 0 ${width} 170`} role="img">
    {[68, 80, 92, 104, 116].map((y) => <line key={y} x1="28" x2={width - 24} y1={y} y2={y} className="staff-line" />)}
    <text x="42" y="112" className={clef === '𝄢' ? 'clef bass' : 'clef'}>{clef}</text><text x="108" y="86" className="meter">{numerator}</text><text x="108" y="108" className="meter">{denominator}</text><text x="128" y="58" className="key-label">{project.keySignature}</text>
    {Array.from({ length: measures + 1 }, (_, index) => { const x = startX + index * measureBeats * pxPerBeat; return <g key={index}><line x1={x} x2={x} y1="68" y2="116" className="bar-line" />{index < measures && <text x={x + 5} y="62" className="measure-number">{index + 1}</text>}</g> })}
    {track.notes.map((note, index) => {
      const spelling = note.spelling ?? fallbackSpelling, x = startX + 18 + onsets[index] * pxPerBeat
      const y = midiToStaffY(note.midi, spelling, track.instrument === 'cello' ? 'bass' : 'treble')
      const next = track.notes[index + 1], nextX = startX + 18 + (onsets[index + 1] ?? onsets[index] + durationToBeats(note.duration)) * pxPerBeat
      return <g key={note.id} className={`note ${note.id === selectedId ? 'selected' : ''} ${index === activeStep ? 'active' : ''}`} onClick={() => onSelect(note.id)}>
        {y >= 110 && <line x1={x - 13} x2={x + 14} y1="116" y2="116" className="ledger" />}{isAccidental(note.midi) && <text x={x - 24} y={y + 6} className="accidental">{spelling === 'flat' ? '♭' : '♯'}</text>}{note.fermata && <text x={x} y={y - 48} textAnchor="middle" className="fermata">𝄐</text>}
        <ellipse cx={x} cy={y} rx="9" ry="6.5" transform={`rotate(-18 ${x} ${y})`} />{note.duration < 1 && <line x1={x + 8} x2={x + 8} y1={y} y2={y - 39} />}{note.duration === 0.125 && <path d={`M ${x + 8} ${y - 39} q 16 7 5 20`} className="note-flag" />}
        {note.tieToNext && next?.midi === note.midi && <path d={`M ${x - 6} ${y + 11} Q ${(x + nextX) / 2} ${y + 28} ${nextX + 6} ${y + 11}`} className="tie" />}<text x={x} y="153" textAnchor="middle" className="pitch-label">{midiToName(note.midi, spelling)}</text>
      </g>
    })}
  </svg></div>
}

function Jianpu({ project, track, selectedId, activeStep, onSelect }: { project: ProjectData; track: Track; selectedId: string | null; activeStep: number; onSelect: (id: string) => void }) {
  const fallback = defaultSpellingForKey(project.keySignature)
  return <div className="jianpu" aria-label={`${track.name}简谱`}>{track.notes.map((note, index) => { const { degree, octave } = midiToJianpu(note.midi, note.spelling ?? fallback); return <button key={note.id} onClick={() => onSelect(note.id)} className={`jianpu-note ${note.id === selectedId ? 'selected' : ''} ${index === activeStep ? 'active' : ''}`}>{note.fermata && <b>𝄐</b>}{octave > 0 && <i className="octave-dot top" />}<span>{degree}</span>{note.duration === 0.5 && <em>—</em>}{note.duration === 1 && <em>———</em>}{note.duration === 0.125 && <u />}{note.tieToNext && <small>⌒</small>}{octave < 0 && <i className="octave-dot bottom" />}</button> })}</div>
}

function Overview({ project, onOpenTrack }: { project: ProjectData; onOpenTrack: (id: string) => void }) {
  const measureBeats = beatsPerMeasure(project.timeSignature), totalBeats = Math.max(measureBeats * 2, ...project.tracks.map((track) => trackDurationBeats(track.notes)))
  const measureCount = Math.ceil(totalBeats / measureBeats)
  return <section className="overview-panel"><div className="overview-heading"><div><span>总谱编排</span><h2>{project.title}</h2></div><p>双击任意声部进入精细编辑</p></div><div className="ruler"><span>小节</span>{Array.from({ length: measureCount }, (_, index) => <i key={index}>{index + 1}</i>)}</div><div className="arrangement" style={{ '--measures': measureCount } as CSSProperties}>
    {project.tracks.map((track) => { const onsets = noteOnsets(track.notes); return <button key={track.id} className="arrangement-row" onDoubleClick={() => onOpenTrack(track.id)}><span className="arrangement-label"><i style={{ background: track.color }} />{track.name}<small>{track.muted ? '已静音' : instrumentMeta[track.instrument].name}</small></span><span className="arrangement-lane">{track.notes.map((note, index) => <b key={note.id} title={midiToName(note.midi, note.spelling)} style={{ left: `${onsets[index] / totalBeats * 100}%`, width: `${Math.max(1.4, durationToBeats(note.duration) / totalBeats * 100)}%`, background: track.color }} />)}</span></button> })}
  </div></section>
}

export default function StudioApp() {
  const [projects, setProjects] = useState<ProjectData[]>(() => loadProjects())
  const [activeProjectId, setActiveProjectId] = useState<string | null>(null), [activeTrackId, setActiveTrackId] = useState<string | null>(null)
  const [editorMode, setEditorMode] = useState<'overview' | 'track'>('overview'), [inputDuration, setInputDuration] = useState<Duration>(0.25)
  const [inputOctave, setInputOctave] = useState(4), [inputSpelling, setInputSpelling] = useState<AccidentalSpelling>('sharp')
  const [selectedNoteId, setSelectedNoteId] = useState<string | null>(null), [playing, setPlaying] = useState(false), [activeStep, setActiveStep] = useState(-1)
  const [saveState, setSaveState] = useState('所有更改已保存'), playbackTimer = useRef<number | undefined>(undefined), midiInput = useRef<HTMLInputElement>(null)
  const project = projects.find((item) => item.id === activeProjectId) ?? null, currentTrack = project?.tracks.find((track) => track.id === activeTrackId) ?? project?.tracks[0] ?? null

  useEffect(() => { saveProjects(projects) }, [projects])
  function updateProject(update: (project: ProjectData) => ProjectData) { if (!activeProjectId) return; setSaveState('正在保存…'); setProjects((current) => current.map((item) => item.id === activeProjectId ? { ...update(item), updatedAt: new Date().toISOString() } : item)); window.setTimeout(() => setSaveState('所有更改已保存'), 260) }
  function openProject(id: string) { const target = projects.find((item) => item.id === id); if (!target) return; setActiveProjectId(id); setActiveTrackId(target.tracks[0]?.id ?? null); setEditorMode('overview'); setSelectedNoteId(null); setInputSpelling(defaultSpellingForKey(target.keySignature)) }
  function createNewProject() { const created = createBlankProject(`未命名作品 ${projects.filter((item) => !item.example).length + 1}`); setProjects((current) => [created, ...current]); setActiveProjectId(created.id); setActiveTrackId(created.tracks[0].id); setEditorMode('overview') }
  function updateTrack(id: string, update: (track: Track) => Track) { updateProject((current) => ({ ...current, tracks: current.tracks.map((track) => track.id === id ? update(track) : track) })) }
  function addTrack(instrument: InstrumentId) { if (!project) return; const track = newTrack(instrument, project.tracks); updateProject((current) => ({ ...current, tracks: [...current.tracks, track] })); setActiveTrackId(track.id) }
  function moveTrack(id: string, direction: -1 | 1) { updateProject((current) => { const tracks = [...current.tracks], index = tracks.findIndex((track) => track.id === id), destination = index + direction; if (index < 0 || destination < 0 || destination >= tracks.length) return current; const [track] = tracks.splice(index, 1); tracks.splice(destination, 0, track); return { ...current, tracks } }) }
  function addNote(baseMidi: number) { if (!currentTrack) return; const midi = baseMidi + (inputOctave - 4) * 12, note = newNote(midi, inputDuration, isAccidental(midi) ? inputSpelling : undefined); updateTrack(currentTrack.id, (track) => ({ ...track, notes: [...track.notes, note] })); setSelectedNoteId(note.id); void import('./audio').then(({ previewNote }) => previewNote(currentTrack.instrument, midi)) }
  function updateSelected(update: (note: NoteEvent) => NoteEvent) { if (!currentTrack || !selectedNoteId) return; updateTrack(currentTrack.id, (track) => ({ ...track, notes: track.notes.map((note) => note.id === selectedNoteId ? update(note) : note) })) }
  function applyDuration(value: Duration) { setInputDuration(value); updateSelected((note) => ({ ...note, duration: value })) }
  function applyAccidental(kind: 'sharp' | 'flat' | 'natural') { setInputSpelling(kind === 'flat' ? 'flat' : 'sharp'); updateSelected((note) => { if (kind === 'natural') return !isAccidental(note.midi) ? { ...note, spelling: undefined } : { ...note, midi: note.midi + (note.spelling === 'flat' ? 1 : -1), spelling: undefined }; if (isAccidental(note.midi)) return { ...note, spelling: kind }; return { ...note, midi: note.midi + (kind === 'sharp' ? 1 : -1), spelling: kind } }) }
  function toggleTie() { if (!currentTrack || !selectedNoteId) return; updateTrack(currentTrack.id, (track) => { const notes = [...track.notes], index = notes.findIndex((note) => note.id === selectedNoteId); if (index < 0) return track; const enabled = !notes[index].tieToNext; notes[index] = { ...notes[index], tieToNext: enabled }; if (enabled && notes[index + 1]?.midi !== notes[index].midi) notes.splice(index + 1, 0, newNote(notes[index].midi, notes[index].duration, notes[index].spelling)); return { ...track, notes } }) }
  function deleteSelected() { if (!currentTrack || !selectedNoteId) return; updateTrack(currentTrack.id, (track) => ({ ...track, notes: track.notes.filter((note) => note.id !== selectedNoteId) })); setSelectedNoteId(null) }
  async function togglePlayback() { if (!project) return; if (playing) { const { stopPlayback } = await import('./audio'); stopPlayback(); if (playbackTimer.current) window.clearTimeout(playbackTimer.current); setPlaying(false); setActiveStep(-1); return } setPlaying(true); const { playTracks } = await import('./audio'); const length = await playTracks(project.tracks, project.bpm, setActiveStep); playbackTimer.current = window.setTimeout(() => { setPlaying(false); setActiveStep(-1) }, length) }
  async function exportMidi() { if (!project) return; const { projectToMidi } = await import('./midi'), bytes = projectToMidi(project.tracks, project.bpm), url = URL.createObjectURL(new Blob([Uint8Array.from(bytes).buffer], { type: 'audio/midi' })), link = document.createElement('a'); link.href = url; link.download = `${project.title.replace(/[\\/:*?"<>|]/g, '-')}.mid`; link.click(); URL.revokeObjectURL(url) }
  async function importMidi(file?: File) { if (!file) return; try { const { midiToProject } = await import('./midi'), imported = midiToProject(await file.arrayBuffer()); updateProject((current) => ({ ...current, bpm: imported.bpm, tracks: imported.tracks })); setActiveTrackId(imported.tracks[0].id); setEditorMode('overview') } catch { setSaveState('MIDI 导入失败') } }

  if (!project) return <Home projects={projects} onCreate={createNewProject} onOpen={openProject} />
  return <main className="app-shell"><header className="topbar"><button className="back-home" onClick={() => setActiveProjectId(null)}>← 作品库</button><div className="brand-mark">S</div><input className="project-title-input" aria-label="作品名称" value={project.title} onChange={(event) => updateProject((current) => ({ ...current, title: event.target.value }))} /><nav><button className={editorMode === 'overview' ? 'nav-item active' : 'nav-item'} onClick={() => setEditorMode('overview')}>总谱</button><button className={editorMode === 'track' ? 'nav-item active' : 'nav-item'} onClick={() => setEditorMode('track')}>声部编辑</button></nav><div className="status-pill"><i /> {saveState}</div></header>
    <section className="workspace-header compact"><div className="project-settings"><label>调号<select aria-label="调号" value={project.keySignature} onChange={(event) => { const key = event.target.value as KeySignature; updateProject((current) => ({ ...current, keySignature: key })); setInputSpelling(defaultSpellingForKey(key)) }}>{(['C', 'G', 'D', 'F', 'B♭', 'E♭'] as KeySignature[]).map((key) => <option key={key}>{key}</option>)}</select></label><label>拍号<select aria-label="拍号" value={project.timeSignature} onChange={(event) => updateProject((current) => ({ ...current, timeSignature: event.target.value as TimeSignature }))}>{(['4/4', '3/4', '6/8'] as TimeSignature[]).map((value) => <option key={value}>{value}</option>)}</select></label></div><div className="transport"><div className="tempo"><span>速度</span><strong>{project.bpm}</strong><small>BPM</small><input aria-label="速度" type="range" min="40" max="200" value={project.bpm} onChange={(event) => updateProject((current) => ({ ...current, bpm: Number(event.target.value) }))} /></div><button className="play-button" onClick={() => void togglePlayback()}>{playing ? '■' : '▶'}</button></div></section>
    <section className="studio-grid"><aside className="track-panel"><div className="panel-title"><span>声部</span><small>{project.tracks.length} TRACKS</small></div>{project.tracks.map((track, index) => <div key={track.id} className={`track-card ${track.id === currentTrack?.id ? 'selected' : ''}`} onClick={() => setActiveTrackId(track.id)} onDoubleClick={() => { setActiveTrackId(track.id); setEditorMode('track') }}><span className="instrument-icon" style={{ background: track.color }}>{instrumentMeta[track.instrument].icon}</span><span className="track-name"><input aria-label={`${track.name}名称`} value={track.name} onClick={(event) => event.stopPropagation()} onChange={(event) => updateTrack(track.id, (current) => ({ ...current, name: event.target.value }))} /><small>{track.notes.length} 个音符 · 双击编辑</small></span><span className="track-actions"><button title="上移声部" disabled={index === 0} onClick={(event) => { event.stopPropagation(); moveTrack(track.id, -1) }}>↑</button><button title="下移声部" disabled={index === project.tracks.length - 1} onClick={(event) => { event.stopPropagation(); moveTrack(track.id, 1) }}>↓</button><button title="静音" className={track.muted ? 'muted' : ''} onClick={(event) => { event.stopPropagation(); updateTrack(track.id, (current) => ({ ...current, muted: !current.muted })) }}>M</button></span></div>)}<div className="add-track-row" aria-label="添加声部">{(['piano', 'violin', 'cello', 'flute'] as InstrumentId[]).map((instrument) => <button key={instrument} className="add-track" onClick={() => addTrack(instrument)}>＋ {instrumentMeta[instrument].name}</button>)}</div><p className="track-help">用 ↑↓ 调整总谱顺序，双击进入声部。</p></aside>
      {editorMode === 'overview' ? <Overview project={project} onOpenTrack={(id) => { setActiveTrackId(id); setEditorMode('track') }} /> : currentTrack && <section className="score-panel"><div className="score-toolbar"><div className="view-switch"><button onClick={() => setEditorMode('overview')}>总谱总览</button><button className="active">{currentTrack.name}</button></div><div className="notation-tools">{durations.map((item) => <button key={item.value} title={item.label} className={inputDuration === item.value ? 'active' : ''} onClick={() => applyDuration(item.value)}>{item.symbol}</button>)}<span /><button title="降号" className={inputSpelling === 'flat' ? 'active' : ''} onClick={() => applyAccidental('flat')}>♭</button><button title="还原号" onClick={() => applyAccidental('natural')}>♮</button><button title="升号" className={inputSpelling === 'sharp' ? 'active' : ''} onClick={() => applyAccidental('sharp')}>♯</button><button title="延音线" onClick={toggleTie}>⌒</button><button title="延音记号" onClick={() => updateSelected((note) => ({ ...note, fermata: !note.fermata }))}>𝄐</button><button title="降低半音" onClick={() => updateSelected((note) => ({ ...note, midi: Math.max(21, note.midi - 1) }))}>−½</button><button title="升高半音" onClick={() => updateSelected((note) => ({ ...note, midi: Math.min(108, note.midi + 1) }))}>＋½</button><button title="删除选中音符" onClick={deleteSelected}>⌫</button><input ref={midiInput} type="file" accept="audio/midi,.mid,.midi" hidden onChange={(event) => void importMidi(event.target.files?.[0])} /><button className="text-tool" onClick={() => midiInput.current?.click()}>导入 MIDI</button><button className="text-tool" onClick={() => void exportMidi()}>导出 MIDI</button></div></div><div className="score-heading"><div><span style={{ background: currentTrack.color }} /><strong>{currentTrack.name}</strong></div><p>{project.keySignature} 大调 · {project.timeSignature} · {selectedNoteId ? '已选中音符' : '点击谱面音符进行编辑'}</p></div><Staff project={project} track={currentTrack} selectedId={selectedNoteId} activeStep={activeStep} onSelect={setSelectedNoteId} /><div className="notation-divider"><span>同步简谱</span></div><Jianpu project={project} track={currentTrack} selectedId={selectedNoteId} activeStep={activeStep} onSelect={setSelectedNoteId} /><div className="keyboard-section"><div className="keyboard-copy"><strong>音符输入</strong><span>选择八度、时值和升降号，再点击琴键</span><label>八度<select aria-label="输入八度" value={inputOctave} onChange={(event) => setInputOctave(Number(event.target.value))}>{[2, 3, 4, 5, 6].map((octave) => <option key={octave}>{octave}</option>)}</select></label></div><div className="keyboard">{pitches.map((baseMidi) => { const midi = baseMidi + (inputOctave - 4) * 12, spelling = isAccidental(midi) ? inputSpelling : 'sharp'; return <button className={isAccidental(midi) ? 'accidental-key' : ''} key={baseMidi} onClick={() => addNote(baseMidi)}><span>{midiToName(midi, spelling)}</span><kbd>{midiToJianpu(midi, spelling).degree}</kbd></button> })}</div></div></section>}
    </section><footer><span>SONORA SCORE · COMPOSER</span><span>作品库 ⇄ 总谱 ⇄ 声部 ⇄ MIDI</span></footer>
  </main>
}
